### ISSUE TITLE
Refine double whole noteheads (part II)

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#25]
The vertical lines of the double whole noteheads do not match the default stem thickness in the `engravingDefaults`. 

![noteheadDoubleWhole](https://user-images.githubusercontent.com/7693447/161085926-80764f0e-4b3b-4107-813b-023ea480acaf.png)

![noteheadDoubleWholeSquare](https://user-images.githubusercontent.com/7693447/161085724-ed895717-2cc2-4bac-8640-99a6ed0964fc.png)

![image](https://user-images.githubusercontent.com/7693447/161090875-065aeafc-e986-4b1c-a9bf-d4aab92889de.png)

I'm not sure if the stem thickness value in the metadata should be adjusted or the glyph.
Currently the `"stemThickness"` is set to 0.11 but should be more like 0.145 (although MuseScore only supports two decimals).

Refers to #19

**Comment by oktophonie** [comment]
The MuseScore default is actually 0.1 now, and I will update the metadata accordingly.

Even assuming the verticals of these notes _should_ match the default width of a stem (Brauvra, for example, doesn't either), what happens when a user wishes to set their stems to any other width? The glyph will not change to match.

We could perhaps experiment with the verticals at 0.1sp, since at least if the stem were made any thicker it could be made to cover the vertical stroke of the notehead and the discrepancy in thickness would be hidden (@Tantacrul) (though I question whether anyone would notice anyway, in practice...)

**Comment by rettinghaus** [comment]
I don't know if your point is a valid argument, because changing the font's default stem thickness only works to a certain degree anyway:

![image](https://user-images.githubusercontent.com/7693447/161217097-98a7c78e-5878-4542-b6fa-e93b29aaff4d.png)

(Thanks for pointing me to Bravura, I will raise the same issue there..)

**Comment by oktophonie** [comment]
Most likely to be addressed via metadata rather than in the design (if at all), in future.
