### ISSUE TITLE
Diamond noteheads intersecting stem in grace notes

### ISSUE THREAD

**Issue by crlbrg** [MuseScoreFonts/Leland#31]
Just noticed that diamond noteheads intersect stems in grace notes, in this case harmonics, and was wondering if this is intended behaviour. Two different results in Dorico and MuseScore.

Dorico:
![image](https://user-images.githubusercontent.com/132436714/236144337-481396ca-1ee3-46ec-87e0-a74bf4bd057c.png)
Musescore: 
![image](https://user-images.githubusercontent.com/132436714/236150530-f58a3582-83a6-461f-b7a7-4f4233e03658.png)

**Comment by crlbrg** [comment]
Also, the placing of the acciaccatura line.

**Comment by oktophonie** [comment]
The slash is drawn contextually by the software and is not really anything to do with the font directly. Its placement in MuseScore is entirely by design.

Regarding the stem: I'm not sure what this is about, and it _seems_ specific to Dorico. The required metadata appears to be correct in Leland though.

**Comment by crlbrg** [comment]
Thank you for the clarification. Will check from Dorico's end.
